name: ontario-rrif-calculator

services:
- name: backend
  source_dir: /backend
  github:
    repo: ZenRasta/Ontario_Taxapp_v2
    branch: main
  run_command: python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT --log-level info
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  health_check:
    http_path: /health
    initial_delay_seconds: 60
    period_seconds: 10
    timeout_seconds: 10
    failure_threshold: 10
  envs:
  - key: PORT
    scope: RUN_TIME
    value: "8080"
  - key: PYTHONPATH
    scope: RUN_TIME
    value: "/app"
  - key: ENVIRONMENT
    scope: RUN_TIME
    value: "production"
  - key: ALLOWED_CORS_ORIGINS
    scope: RUN_TIME
    value: "*"
  - key: DB_URL
    scope: RUN_TIME
    value: "sqlite+aiosqlite:///app/rrif_prod.db"
  - key: TAX_YEARS_FILE
    scope: RUN_TIME
    value: "data/tax_years.yml"
  - key: OPENROUTER_API_KEY
    scope: RUN_TIME
    value: "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"
  - key: OPENROUTER_MODEL
    scope: RUN_TIME
    value: "openai/gpt-4o-mini"
  - key: OPENROUTER_BASE_URL
    scope: RUN_TIME
    value: "https://openrouter.ai/api/v1"

static_sites:
- name: frontend
  github:
    repo: ZenRasta/Ontario_Taxapp_v2
    branch: main
  build_command: echo "Static site deployment"
  output_dir: /
  index_document: index.html
