name: ontario-rrif-calculator

services:
- name: backend
  source_dir: /backend
  github:
    repo: ZenRasta/Ontario_Taxapp_v2
    branch: main
  run_command: python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT --log-level info
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  health_check:
    http_path: /health
    initial_delay_seconds: 60
    period_seconds: 10
    timeout_seconds: 10
    failure_threshold: 10
  envs:
  - key: PORT
    scope: RUN_TIME
    value: "8080"
  - key: PYTHONPATH
    scope: RUN_TIME
    value: "/app"
  - key: ENVIRONMENT
    scope: RUN_TIME
    value: "production"
  - key: ALLOWED_CORS_ORIGINS
    scope: RUN_TIME
    value: "*"
  - key: DB_URL
    scope: RUN_TIME
    value: "sqlite+aiosqlite:///app/rrif_prod.db"
  - key: TAX_YEARS_FILE
    scope: RUN_TIME
    value: "data/tax_years.yml"
  - key: OPENAI_API_KEY
    scope: RUN_TIME
    value: "${OPENAI_API_KEY}"
  - key: RESEND_API_KEY
    scope: RUN_TIME
    value: "re_XFws7iY9_EDwGBknV4Vnugutfb6do3mCN"
  - key: FROM_EMAIL
    scope: RUN_TIME
    value: "oascalculator@ontariotaxapp.com"
  - key: FROM_NAME
    scope: RUN_TIME
    value: "Ontario Tax App - OAS Calculator"

static_sites:
- name: frontend
  source_dir: /frontend
  github:
    repo: ZenRasta/Ontario_Taxapp_v2
    branch: main
  build_command: npm ci && npm run build
  output_dir: dist
  index_document: index.html
  environment_slug: node-js
  envs:
  - key: NODE_ENV
    scope: BUILD_TIME
    value: "production"
  - key: VITE_API_URL
    scope: BUILD_TIME
    value: "https://ontario-rrif-calculator-backend.ondigitalocean.app/api/v1"
