alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
name: whale-app
region: nyc
services:
- environment_slug: python
  envs:
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    value: postgresql://user:password@localhost:5432/retirement_sessions_db
  - key: TAX_YEARS_FILE
    scope: RUN_AND_BUILD_TIME
    value: backend/data/tax_years.yml
  - key: SESSION_DATA_TTL_HOURS
    scope: RUN_AND_BUILD_TIME
    value: "24"
  - key: OPENAI_API_KEY
    scope: RUN_AND_BUILD_TIME
    value: ${OPENAI_API_KEY}
  - key: RESEND_API_KEY
    scope: RUN_AND_BUILD_TIME
    value: re_XFws7iY9_EDwGBknV4Vnugutfb6do3mCN
  - key: FROM_EMAIL
    scope: RUN_AND_BUILD_TIME
    value: oascalculator@ontariotaxapp.com
  - key: FROM_NAME
    scope: RUN_AND_BUILD_TIME
    value: Ontario Tax App - OAS Calculator
  github:
    branch: main
    deploy_on_push: true
    repo: ZenRasta/Ontario_Taxapp_v2
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  name: ontario-taxapp-v2
  source_dir: /
  build_command: |
    # Build the frontend first
    cd frontend && npm ci && npm run build
    # Install Python dependencies
    cd .. && pip install -r requirements.txt
  run_command: python main.py
