name: ontario-rrif-calculator

static_sites:
- name: frontend
  github:
    repo: ZenRasta/Ontario_Taxapp_v2
    branch: main
  build_command: echo "Static site deployment"
  output_dir: /
  index_document: index.html

services:
- name: backend
  source_dir: /backend
  github:
    repo: ZenRasta/Ontario_Taxapp_v2
    branch: main
  run_command: python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  health_check:
    http_path: /docs
  envs:
  - key: PORT
    scope: RUN_TIME
    value: "8080"
  - key: PYTHONPATH
    scope: RUN_TIME
    value: "/app"
