name: ontario-rrif-calculator

services:
- name: web
  github:
    repo: ZenRasta/Ontario_Taxapp_v2
    branch: main
  dockerfile_path: Dockerfile
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  health_check:
    http_path: /health
    initial_delay_seconds: 60
    period_seconds: 10
    timeout_seconds: 10
    failure_threshold: 10
  envs:
  - key: PORT
    scope: RUN_TIME
    value: "8080"
  - key: NODE_ENV
    scope: RUN_TIME
    value: "production"
  - key: PYTHONPATH
    scope: RUN_TIME
    value: "/app/backend"
  - key: ENVIRONMENT
    scope: RUN_TIME
    value: "production"
  - key: ALLOWED_CORS_ORIGINS
    scope: RUN_TIME
    value: "*"
  - key: DB_URL
    scope: RUN_TIME
    value: "sqlite+aiosqlite:///app/backend/rrif_prod.db"
  - key: TAX_YEARS_FILE
    scope: RUN_TIME
    value: "backend/data/tax_years.yml"
  - key: OPENAI_API_KEY
    scope: RUN_TIME
    value: "${OPENAI_API_KEY}"
  - key: RESEND_API_KEY
    scope: RUN_TIME
    value: "re_XFws7iY9_EDwGBknV4Vnugutfb6do3mCN"
  - key: FROM_EMAIL
    scope: RUN_TIME
    value: "oascalculator@ontariotaxapp.com"
  - key: FROM_NAME
    scope: RUN_TIME
    value: "Ontario Tax App - OAS Calculator"
