name: ontario-rrif-calculator

services:
- name: backend
  github:
    repo: ZenRasta/Ontario_Taxapp_v2
    branch: main
  dockerfile_path: backend/Dockerfile
  source_dir: backend
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /api
    preserve_path_prefix: true
  health_check:
    http_path: /api/v1/health
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    failure_threshold: 3
  envs:
  - key: ENVIRONMENT
    scope: RUN_TIME
    value: "production"
  - key: ALLOWED_CORS_ORIGINS
    scope: RUN_TIME
    value: "*"
  - key: DB_URL
    scope: RUN_TIME
    value: "sqlite+aiosqlite:///app/rrif_prod.db"
  - key: TAX_YEARS_FILE
    scope: RUN_TIME
    value: "/app/data/tax_years.yml"
  - key: OPENAI_API_KEY
    scope: RUN_TIME
    value: "${OPENAI_API_KEY}"
  - key: RESEND_API_KEY
    scope: RUN_TIME
    value: "re_XFws7iY9_EDwGBknV4Vnugutfb6do3mCN"
  - key: FROM_EMAIL
    scope: RUN_TIME
    value: "oascalculator@ontariotaxapp.com"
  - key: FROM_NAME
    scope: RUN_TIME
    value: "Ontario Tax App - OAS Calculator"

- name: frontend
  github:
    repo: ZenRasta/Ontario_Taxapp_v2
    branch: main
  build_command: npm run --workspace frontend build
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  health_check:
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    failure_threshold: 3
  envs:
  - key: PORT
    scope: RUN_TIME
    value: "8080"
  - key: NODE_ENV
    scope: RUN_TIME
    value: "production"
