name: whale-app
region: nyc
features:
  - buildpack-stack=ubuntu-22

#######################################
# 1️⃣  PYTHON BACK-END SERVICE
#######################################
services:
  - name: ontario-taxapp-v2          # <-- keep your existing container
    environment_slug: python
    source_dir: /
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb

    build_command: |
      pip install -r requirements.txt            # API only
    run_command: >
      gunicorn --worker-tmp-dir /dev/shm
      --config gunicorn.conf.py
      main:app --bind 0.0.0.0:8080

    ###################################
    # ROUTES → where traffic goes in
    ###################################
    routes:
      - path: /v1                              # NEW
      - path: /api                             # legacy

    ###################################
    # ENV VARS (unchanged)
    ###################################
    envs:
      - key: DATABASE_URL
        value: postgresql://user:password@localhost:5432/retirement_sessions_db
        scope: RUN_AND_BUILD_TIME
      - key: TAX_YEARS_FILE
        value: backend/data/tax_years.yml
        scope: RUN_AND_BUILD_TIME
      - key: SESSION_DATA_TTL_HOURS
        value: "24"
        scope: RUN_AND_BUILD_TIME
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
        scope: RUN_AND_BUILD_TIME
      - key: RESEND_API_KEY
        value: re_XFws7iY9_EDwGBknV4Vnugutfb6do3mCN
        scope: RUN_AND_BUILD_TIME
      - key: FROM_EMAIL
        value: oascalculator@ontariotaxapp.com
        scope: RUN_AND_BUILD_TIME
      - key: FROM_NAME
        value: Ontario Tax App - OAS Calculator
        scope: RUN_AND_BUILD_TIME

#######################################
# 2️⃣  REACT STATIC SITE
#######################################
static_sites:
  - name: frontend                       # <-- new component
    source_dir: frontend                 # location of package.json
    build_command: |
      npm ci && npm run build
    output_dir: build
    catchall_document: index.html

    ###################################
    # ROUTE – everything else
    ###################################
    routes:
      - path: /                          # SPA root
