name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: abatilo/actions-poetry@v2
      - name: Install dependencies
        run: cd backend && poetry install --no-interaction
      - name: Check PyYAML availability
        run: python -c "import yaml, sys; print('PyYAML:', yaml.__version__)"
      - name: Run tests
        run: cd backend && poetry run pytest
